import {
  GraduationCap, BookOpen, Video, FileText, Monitor, Globe, Laptop, Presentation,
  Users, Award, BookMarked, Library, School, Lightbulb, Brain, Rocket, Target,
  Trophy, Star, Sparkles, MessageSquare, Code, Database, Smartphone, Camera,
  Music, Palette, Calculator, Beaker, Heart, Flame, Zap, Crown, Shield, Lock,
  Unlock, Key, Mail, Phone, MapPin, Map, Compass, Navigation, Wifi, Bluetooth,
  Signal, Printer, Cpu, HardDrive, Server, Cloud, Upload, Download, Folder,
  File, FileCode, FileImage, Save, Trash2, Edit, Pencil, Pen, Plus,
  Minus, X, Check, ChevronRight, ArrowRight, TrendingUp, BarChart3,
  PieChart, Activity, Settings, Wrench, Hammer, Scissors, Paintbrush,
  Droplet, Sun, Moon, CloudRain, Snowflake, Wind, Thermometer, Umbrella, Coffee,
  Pizza, Utensils, Apple, Gift, ShoppingCart, ShoppingBag, CreditCard, DollarSign,
  Coins, Wallet, Tag, Package, Truck, Plane, Train, Car, Bike, Bus, Ship,
  Anchor, Home, Building, Building2, Store, Hospital, Hotel, Factory, Warehouse,
  TreePine, Flower2, Leaf, Gem, Diamond, Circle, Square, Triangle,
  Hexagon, Box, Layers, Copy, Clipboard, ClipboardList, BookText, Newspaper,
  Bookmark, Flag, Bell, BellRing, AlarmClock, Clock, Calendar, Timer, Hourglass,
  Watch, Handshake, BriefcaseBusiness, Languages, Amphora, PencilRuler, ScrollText, Scroll,
  // Backward compatibility
  ArrowUpSquare, Briefcase, PuzzleIcon, Scale, ShieldCheck,
  HandMetal, Image, Film, Megaphone, Ticket,
  type LucideIcon,
} from "lucide-react";

export type IconComponent = LucideIcon;

export const iconMap: Record<string, IconComponent> = {
  // Map old Heroicon names to new Lucide icons (backward compatibility)
  AcademicCapIcon: GraduationCap,
  ArrowUpOnSquareIcon: ArrowUpSquare,
  BeakerIcon: Beaker,
  BookOpenIcon: BookOpen,
  BriefcaseIcon: Briefcase,
  BuildingOfficeIcon: Building2,
  CalculatorIcon: Calculator,
  ChatBubbleLeftRightIcon: MessageSquare,
  ClipboardDocumentListIcon: ClipboardList,
  CodeBracketIcon: Code,
  ComputerDesktopIcon: Monitor,
  CpuChipIcon: Cpu,
  CurrencyDollarIcon: DollarSign,
  GlobeAltIcon: Globe,
  HeartIcon: Heart,
  HomeModernIcon: Home,
  LanguageIcon: Languages,
  LightBulbIcon: Lightbulb,
  MusicalNoteIcon: Music,
  PaintBrushIcon: Palette,
  PuzzlePieceIcon: PuzzleIcon,
  RocketLaunchIcon: Rocket,
  ScaleIcon: Scale,
  ShieldCheckIcon: ShieldCheck,
  SparklesIcon: Sparkles,
  TrophyIcon: Trophy,
  UserGroupIcon: Users,
  WrenchScrewdriverIcon: Wrench,
  CakeIcon: Coffee,
  ChartBarIcon: BarChart3,
  FilmIcon: Film,
  FireIcon: Flame,
  FlagIcon: Flag,
  FolderIcon: Folder,
  HandRaisedIcon: HandMetal,
  MapIcon: Map,
  MegaphoneIcon: Megaphone,
  NewspaperIcon: Newspaper,
  PhotoIcon: Image,
  PresentationChartLineIcon: Presentation,
  ShoppingBagIcon: ShoppingBag,
  StarIcon: Star,
  SunIcon: Sun,
  TagIcon: Tag,
  TicketIcon: Ticket,
  VideoCameraIcon: Video,
  WifiIcon: Wifi,

  // Direct Lucide icon names (new icon picker)
  GraduationCap, BookOpen, Video, FileText, Monitor, Globe, Laptop, Presentation,
  Users, Award, BookMarked, Library, School, Lightbulb, Brain, Rocket, Target,
  Trophy, Star, Sparkles, MessageSquare, Code, Database, Smartphone, Camera,
  Music, Palette, Calculator, Beaker, Heart, Flame, Zap, Crown, Shield, Lock,
  Unlock, Key, Mail, Phone, MapPin, Map, Compass, Navigation, Wifi, Bluetooth,
  Signal, Printer, Cpu, HardDrive, Server, Cloud, Upload, Download, Folder,
  File, FileCode, FileImage, Save, Trash: Trash2, Edit, Pencil, Pen, Plus,
  Minus, X, Check, ChevronRight, ArrowRight, TrendingUp, BarChart: BarChart3,
  PieChart, Activity, Settings, Wrench, Hammer, Scissors, Brush: Paintbrush,
  Droplet, Sun, Moon, CloudRain, Snowflake, Wind, Thermometer, Umbrella, Coffee,
  Pizza, Utensils, Apple, Gift, ShoppingCart, ShoppingBag, CreditCard, DollarSign,
  Coins, Wallet, Tag, Package, Truck, Plane, Train, Car, Bike, Bus, Ship,
  Anchor, Home, Building, Building2, Store, Hospital, Hotel, Factory, Warehouse,
  TreePine, Flower: Flower2, Leaf, Gem, Diamond, Circle, Square, Triangle,
  Hexagon, Box, Layers, Copy, Clipboard, ClipboardList, BookText, Newspaper,
  Bookmark, Flag, Bell, BellRing, AlarmClock, Clock, Calendar, Timer, Hourglass,
  Watch, Handshake, BriefcaseBusiness, Languages, Amphora, PencilRuler, ScrollText, Scroll,
};

export function getIconComponent(iconName: string): IconComponent {
  return iconMap[iconName] || BookOpen;
}
